name: drawing_animation
description: An dart-only library for gradually painting SVG path objects on canvas (drawing line animation).
version: 1.0.1
repository: https://github.com/maranix/flutter_drawing_animation
homepage: https://twitter.com/cahaucks

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  path_parsing: ^1.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
