name: draw_svg
description: An dart-only library for gradually painting SVG path objects on canvas (drawing line animation).
version: 1.0.0
repository: https://github.com/maranix/draw_svg
homepage: https://twitter.com/only_maranix

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  path_parsing: ^1.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  meta: ^1.11.0
  mockito: ^5.4.4
